/**
 * Build the browser client bundle and inline the static assets.
 *
 * There is intentionally no Vite/SPA build: the worker serves exactly two
 * static files (styles.css, webauthn.js) from memory via src/assets.gen.ts,
 * so every response — including static ones — carries the security headers
 * middleware. Run via `npm run build:client` (also runs before dev/deploy).
 */
import esbuild from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";

await esbuild.build({
  entryPoints: ["src/client/webauthn.ts"],
  bundle: true,
  minify: true,
  format: "iife",
  target: "es2020",
  outfile: "public/webauthn.js",
  logLevel: "warning",
});

const css = readFileSync("public/styles.css", "utf8");
const js = readFileSync("public/webauthn.js", "utf8");

writeFileSync(
  "src/assets.gen.ts",
  `// Generated by scripts/build-client.mjs — do not edit by hand.\n` +
    `export const STYLES_CSS = ${JSON.stringify(css)};\n` +
    `export const WEBAUTHN_JS = ${JSON.stringify(js)};\n`,
);

console.log(
  `client built: webauthn.js ${(js.length / 1024).toFixed(1)}kb, styles.css ${(css.length / 1024).toFixed(1)}kb`,
);
