/**
 * Build the browser client bundle and inline the static assets.
 *
 * There is intentionally no Vite/SPA build: the worker serves the static
 * files (themes/*.css, webauthn.js) from memory via src/assets.gen.ts,
 * so every response — including static ones — carries the security headers
 * middleware. Run via `npm run build:client` (also runs before dev/deploy).
 */
import esbuild from "esbuild";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

await esbuild.build({
  entryPoints: ["src/client/webauthn.ts"],
  bundle: true,
  minify: true,
  format: "iife",
  target: "es2020",
  outfile: "public/webauthn.js",
  logLevel: "warning",
});

const themeFiles = readdirSync("public/themes").filter((f) =>
  f.endsWith(".css"),
);
const themes = Object.fromEntries(
  themeFiles.map((f) => [f.replace(/\.css$/, ""), readFileSync(`public/themes/${f}`, "utf8")]),
);
const js = readFileSync("public/webauthn.js", "utf8");

writeFileSync(
  "src/assets.gen.ts",
  `// Generated by scripts/build-client.mjs — do not edit by hand.\n` +
    `export const THEMES_CSS: Record<string, string> = ${JSON.stringify(themes)};\n` +
    `export const WEBAUTHN_JS = ${JSON.stringify(js)};\n`,
);

console.log(
  `client built: webauthn.js ${(js.length / 1024).toFixed(1)}kb, ${themeFiles.length} themes`,
);
